# Generated by Django 6.0.3 on 2026-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('adhd', 'ADHD'), ('dyslexia', 'Dyslexia')], default='normal', max_length=20),
        ),
    ]
