# Generated by Django 6.0.3 on 2026-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testresult_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='cursor_movements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='idle_time',
            field=models.FloatField(default=0),
        ),
    ]
