# Generated by Django 6.0.3 on 2026-04-23 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_testresult_cursor_movements_testresult_idle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
