# Generated by Django 6.0.3 on 2026-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_testresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='idle_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='movement_rate',
            field=models.FloatField(default=0),
        ),
    ]
