# Generated by Django 6.0.3 on 2026-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_testresult_idle_rate_testresult_movement_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='testresult',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='analysis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testresult',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('science', 'Science'), ('memory', 'Memory')], default='math', max_length=20),
        ),
    ]
