# Generated by Django 6.0.3 on 2026-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_testresult_options_testresult_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='subject',
            field=models.CharField(default='Combined Test', max_length=100),
        ),
    ]
