# Generated by Django 6.0.3 on 2026-05-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_testresult_options_alter_testresult_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='attention_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='face_missing_count',
            field=models.IntegerField(default=0),
        ),
    ]
