# Generated by Django 6.0.3 on 2026-05-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_testresult_attention_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='attention_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='face_missing_count',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='subject',
        ),
    ]
