# Generated by Django 6.0.3 on 2026-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_testresult_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='attention_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='subject',
            field=models.CharField(default='3-5', max_length=50),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='load_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_taken',
            field=models.FloatField(default=0),
        ),
    ]
