"""
Django-ready facial stress inference helpers.

Load the artifact generated by train_facial_stress_model.py and classify a
single webcam frame or uploaded face image as Stressed or Relaxed.
"""

from __future__ import annotations

import base64
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Optional

import cv2
import joblib
import numpy as np
import pandas as pd
from django.conf import settings

from train_facial_stress_model import FEATURE_NAMES, FaceMeshExtractor, STRESSED_LABEL


DEFAULT_MODEL_PATH = (
    Path(settings.BASE_DIR)
    / "model_artifacts"
    / "facial_stress_detector"
    / "facial_stress_detector.joblib"
)


@lru_cache(maxsize=1)
def load_facial_stress_bundle(model_path: Optional[str] = None) -> Dict[str, Any]:
    artifact_path = Path(model_path) if model_path else DEFAULT_MODEL_PATH
    if not artifact_path.exists():
        raise FileNotFoundError(
            "Facial stress model artifact was not found. Train the model first with "
            f"train_facial_stress_model.py and save it to: {artifact_path}"
        )
    return joblib.load(artifact_path)


@lru_cache(maxsize=1)
def get_face_mesh_extractor() -> FaceMeshExtractor:
    return FaceMeshExtractor()


def decode_image_bytes(image_bytes: bytes) -> np.ndarray:
    image_array = np.frombuffer(image_bytes, dtype=np.uint8)
    image = cv2.imdecode(image_array, cv2.IMREAD_COLOR)
    if image is None:
        raise ValueError("Could not decode image bytes into an OpenCV image.")
    return image


def decode_data_uri_image(data_uri: str) -> np.ndarray:
    encoded = data_uri.split(",", 1)[1] if "," in data_uri else data_uri
    return decode_image_bytes(base64.b64decode(encoded))


def predict_facial_stress_from_bgr_image(
    image: np.ndarray, model_path: Optional[str] = None
) -> Dict[str, Any]:
    bundle = load_facial_stress_bundle(model_path)
    extractor = get_face_mesh_extractor()
    features = extractor.extract_features_from_bgr_image(image)

    if features is None:
        return {
            "face_detected": False,
            "label": "Unknown",
            "stressed_probability": None,
            "threshold": bundle["stressed_probability_threshold"],
            "features": None,
        }

    feature_frame = pd.DataFrame([features], columns=FEATURE_NAMES)
    model = bundle["pipeline"]
    class_labels = list(model.classes_)
    stressed_index = class_labels.index(STRESSED_LABEL)
    stressed_probability = float(model.predict_proba(feature_frame)[0][stressed_index])
    threshold = float(bundle["stressed_probability_threshold"])
    label = STRESSED_LABEL if stressed_probability >= threshold else "Relaxed"

    return {
        "face_detected": True,
        "label": label,
        "stressed_probability": round(stressed_probability, 4),
        "threshold": round(threshold, 4),
        "features": {
            feature_name: round(float(value), 6)
            for feature_name, value in zip(FEATURE_NAMES, features)
        },
    }


def predict_facial_stress_from_image_bytes(
    image_bytes: bytes, model_path: Optional[str] = None
) -> Dict[str, Any]:
    image = decode_image_bytes(image_bytes)
    return predict_facial_stress_from_bgr_image(image, model_path)


def predict_facial_stress_from_data_uri(
    data_uri: str, model_path: Optional[str] = None
) -> Dict[str, Any]:
    image = decode_data_uri_image(data_uri)
    return predict_facial_stress_from_bgr_image(image, model_path)
